// <auto-generated />
using System;
using MedicalNewsVerifier.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalNewsVerifier.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602170006_SyncSuspiciousFeatureKindId")]
    partial class SyncSuspiciousFeatureKindId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.AnalysisRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("HeuristicReliabilityScore")
                        .HasColumnType("integer");

                    b.Property<int?>("LlmAlignmentScore")
                        .HasColumnType("integer");

                    b.Property<string>("LlmSummary")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("NewsSubmissionId")
                        .HasColumnType("integer");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NewsSubmissionId");

                    b.ToTable("AnalysisRecords");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.NewsSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NewsText")
                        .IsRequired()
                        .HasMaxLength(15000)
                        .HasColumnType("character varying(15000)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ContentFingerprint")
                        .IsUnique();

                    b.ToTable("NewsSubmissions");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.OfficialPublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TrustedSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("TrustedSourceId");

                    b.ToTable("OfficialPublications");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.OfficialPublicationMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisRecordId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfficialPublicationId")
                        .HasColumnType("integer");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OfficialPublicationId");

                    b.HasIndex("AnalysisRecordId", "OfficialPublicationId")
                        .IsUnique();

                    b.ToTable("OfficialPublicationMatches");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.SuspiciousFeatureKindDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CssToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("SuspiciousFeatureKindDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Emotional",
                            CssToken = "emotional",
                            Description = "Текст содержит эмоциональную окраску и призван влиять на чувства.",
                            Title = "Эмоционально окрашенная лексика"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Manipulative",
                            CssToken = "manipulative",
                            Description = "Выкристаллизованные словоформы, направленные на управление восприятием.",
                            Title = "Манипулятивные выражения"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Evaluative",
                            CssToken = "evaluative",
                            Description = "Слова с оценкой, создающие субъективное впечатление.",
                            Title = "Оценочная лексика"
                        },
                        new
                        {
                            Id = 4,
                            Code = "UppercaseWord",
                            CssToken = "uppercase",
                            Description = "Слова или фразы, полностью написанные заглавными буквами.",
                            Title = "Слова в верхнем регистре"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Exclamation",
                            CssToken = "exclamation",
                            Description = "Восклицательные знаки, усиливающие эмоциональность.",
                            Title = "Восклицательные знаки"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Question",
                            CssToken = "question",
                            Description = "Вопросы, побуждающие к сомнению или уточнению.",
                            Title = "Вопросительные знаки"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Link",
                            CssToken = "source",
                            Description = "Адреса и гиперссылки в тексте.",
                            Title = "Ссылки"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Date",
                            CssToken = "date",
                            Description = "Упоминания дат и временных меток.",
                            Title = "Даты"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Number",
                            CssToken = "number",
                            Description = "Числа и количественные обозначения.",
                            Title = "Числовые данные"
                        },
                        new
                        {
                            Id = 10,
                            Code = "SourceCue",
                            CssToken = "source",
                            Description = "Упоминания источников и ссылок на авторитеты.",
                            Title = "Указание на источник"
                        },
                        new
                        {
                            Id = 11,
                            Code = "PythonHeuristic",
                            CssToken = "python",
                            Description = "Признаки, обнаруженные дополнительным Python-модулем.",
                            Title = "Формулировки повышенного риска"
                        });
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.SuspiciousFragment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureKindId")
                        .HasColumnType("integer")
                        .HasColumnName("FeatureKind");

                    b.Property<string>("FragmentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRecordId");

                    b.HasIndex("FeatureKindId");

                    b.ToTable("SuspiciousFragments");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.TrustedSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrustedSources");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.AnalysisRecord", b =>
                {
                    b.HasOne("MedicalNewsVerifier.Web.Models.NewsSubmission", "NewsSubmission")
                        .WithMany("AnalysisRecords")
                        .HasForeignKey("NewsSubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewsSubmission");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.OfficialPublication", b =>
                {
                    b.HasOne("MedicalNewsVerifier.Web.Models.TrustedSource", "TrustedSource")
                        .WithMany()
                        .HasForeignKey("TrustedSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrustedSource");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.OfficialPublicationMatch", b =>
                {
                    b.HasOne("MedicalNewsVerifier.Web.Models.AnalysisRecord", "AnalysisRecord")
                        .WithMany("OfficialPublicationMatches")
                        .HasForeignKey("AnalysisRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalNewsVerifier.Web.Models.OfficialPublication", "OfficialPublication")
                        .WithMany()
                        .HasForeignKey("OfficialPublicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisRecord");

                    b.Navigation("OfficialPublication");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.SuspiciousFragment", b =>
                {
                    b.HasOne("MedicalNewsVerifier.Web.Models.AnalysisRecord", "AnalysisRecord")
                        .WithMany("SuspiciousFragments")
                        .HasForeignKey("AnalysisRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalNewsVerifier.Web.Models.SuspiciousFeatureKindDefinition", "FeatureKindDefinition")
                        .WithMany()
                        .HasForeignKey("FeatureKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisRecord");

                    b.Navigation("FeatureKindDefinition");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.AnalysisRecord", b =>
                {
                    b.Navigation("OfficialPublicationMatches");

                    b.Navigation("SuspiciousFragments");
                });

            modelBuilder.Entity("MedicalNewsVerifier.Web.Models.NewsSubmission", b =>
                {
                    b.Navigation("AnalysisRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
